### ISSUE TITLE
[Feature]: `vfox` should remind user to update twice when update old format plugins.

### ISSUE THREAD

**Issue by fangzhengjin** [version-fox/vfox#231]
**Version**
0.4.1
**OS**
macOS

**Describe the bug**
first run `vfox update -a`

go -> 0.0.3
java -> 0.4.1
nodejs -> 0.0.6
python -> 0.0.4

second run `vfox update -a`
go -> 0.1.1
nodejs -> 0.3.0
python -> 0.1.2

**Screenshots[optional]**
<img width="640" alt="image" src="https://github.com/version-fox/vfox/assets/12680972/10e6f708-bd25-4513-9718-d61a1de87eeb">

**Comment by aooohan** [comment]
As I mentioned in the [0.3.0 release](https://github.com/version-fox/vfox/releases/tag/v0.3.0), this is because the plugin system has been refactored. 

As `golang` you mentioned in the picture, it's an old format plugin that was installed a long time ago.  As you can see, it is still a single file `golang.lua`. So for this kind of installed plugin, the upgrade needs to be performed twice. But for the new format plugin, it only needs to be done once. This is not an issue.

**Comment by fangzhengjin** [comment]
> As I mentioned in the [0.3.0 release](https://github.com/version-fox/vfox/releases/tag/v0.3.0), this is because the plugin system has been refactored.
> 
> As `golang` you mentioned in the picture, it's an old format plugin that was installed a long time ago. As you can see, it is still a single file `golang.lua`. So for this kind of installed plugin, the upgrade needs to be performed twice. But for the new format plugin, it only needs to be done once. This is not an issue.

For the old version of the plug -in, should `vfox` actively remind users that the user executes the plug -in upgrade command again? Or the program automatically re -executes the plug -in upgrade command?

**Comment by aooohan** [comment]
> should `vfox` actively remind users that the user executes the plug -in upgrade command again? 

Good idea, really should be reminded.
