### ISSUE TITLE
Can't use java/adoptium-jdk

### ISSUE THREAD

**Issue by liquidiert** [version-fox/vfox#25]
**Version**
0.2.1

**OS**
Linux PopOS 22.04

**Describe the bug**
After adding java/adoptium-jdk I can't install or use java versions. Only error message I get is:
```text
java not supported, error: java not installed
``` 
vfox search for java works tho and I can install a version via search. It downloads the sdk but vfox use throws the same error.

*Sidenote*: a `--debug` flag would be nice so you can check what might be wrong on the fly

**Comment by aooohan** [comment]
Hmm, you can't use `java` as sdk-name because of `vfox` use plugin filename `adoptium-jdk` as sdk-name before <= 0.2.1.
I've fixed this bug, using the name in the plugin as the sdk-name. b221f57e35667a1847504da11abc708a85dbd8b5. I'll be doing a 0.2.2 release this week.
Now, you can try again following steps:
```bash
# remove old plugin
vfox remove adoptium-jdk
# add new one and set an alias
vfox add --alias java java/adoptium-jdk 

```

> Sidenote: a --debug flag would be nice so you can check what might be wrong on the fly

Good idea. I've created an issue for this #26

**Comment by aooohan** [comment]
0.2.2 has been released, so this issue is closed
