### ISSUE TITLE
Upgrade of the SDK installed from the nodejs/npmmirror source has failed.

### ISSUE THREAD

**Issue by xxnuo** [version-fox/vfox#85]
**Version**
The version you are currently using 0.2.4
**OS**
Windows

**Describe the bug**
```bash
> vfox add nodejs/npmmirror
Loading plugin from https://version-fox.github.io/version-fox-plugins/nodejs/npmmirror.lua...
Checking plugin...
plugin nodejs already exists

> vfox update nodejs
Checking https://raw.githubusercontent.com/version-fox/version-fox-plugins/main/node/node.lua plugin...
fetch plugin failed, err: file not found

> vfox update nodejs/npmmirror
nodejs/npmmirror plugin not installed
```

**Comment by Chance-fyi** [comment]
The plugin names `nodejs/nodejs` and `nodejs/npmmirror` are identical, both being named `nodejs`. Due to this conflict, only one of these plugins can be installed.

The plugin `nodejs/nodejs` has been renamed from its previous designation, which was `node/node`. Therefore, the `updateUrl` does not exist.

**Comment by aooohan** [comment]
This is a problem caused by the renaming of the plug-in a long time ago. There are currently two ways to solve it,
-  1. Uninstall and reinstall
-  2. Manually modify `updateUrl` property in the plug-in `$HOME/.version-fox/plugin/npmmirror.lua`

**Comment by xxnuo** [comment]
Yes, I found this to be the old version of vfox uninstalled the old addons that were not removed. It worked fine after reinstallation of the nodejs sdk.
